Adds ability to remove deprecated instrumentation files post installation
newrelic/newrelic-dotnet-agent pull request #1104
Opened 2022-05-20 01:40 UTC by jaffinito

## Description

- Updates MSI installer custom actions to remove the  deprecated logging instrumentation files from their default locations (what we have access to).  This is done using a preexisting system that won't throw errors if the files don't exist - it already has several.
- Updates the Azure  Site Extension script to add a new function that removes deprecated files .  This is called at the end of the install script.  Uses `ErrorAction Ignore` to prevent any errors from causing problems like in other areas of the script.
- Updates both the RPM and DEB install scripts to attempt to remove deprecated instrumentation from the `$NEWRELIC_HOME` directory (available in the script already).    Uses `2> /dev/null` to prevent any errors from causing problems like in other areas of the script.

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

2022-05-20 17:54 UTC, jaffinito commented
Reran the logging tests locally in release mode and they all passed on the first go.

2022-05-20 17:56 UTC, JcolemanNR requested changes
Looks reasonable! I believe this will reduce the likelihood of deprecated instrumentation being encountered. Needs changelog

2022-05-24 16:46 UTC, JcolemanNR approved these changes

2022-05-24 21:35 UTC, michaelgoin approved these changes
👍

2022-05-25 20:29 UTC, vuqtran88 approved these changes

2022-05-26 00:38 UTC, merged