Updates the Microsoft.AspNetCore.Mvc.Core reference to a safer version.
newrelic/newrelic-dotnet-agent pull request #1108
Opened 2022-05-25 22:43 UTC by vuqtran88

## Description

Snyk scan reported the agent uses the version of Microsoft.AspNetCore.Mvc.Core that has security issue. Even though the agent references this package version, but actual version of the package that would be loaded is the version specified from the customer's application. The agent targets the lowest version for supportability purposes.

Since the AspNetCore wrapper targets netstandard2.0 so whatever the applications use the AspNetCore wrapper won’t be using the Microsoft.AspNetCore.Mvc.Core version lower than 2.0.0. Because of this, update the package reference is still a safe change to overcome Snyk scan.

2022-05-25 22:51 UTC, JcolemanNR requested changes
The SNYK alert flagged Microsoft.AspNetCore.Hosting@2.0.0 as well

2022-05-25 22:51 UTC, JcolemanNR commented on src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/AspNetCore.csproj
>  		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.0.0" />
This package was flagged by SNYK as well

2022-05-25 23:13 UTC, JcolemanNR commented on src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/AspNetCore.csproj
>  		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.0.0" />
It looks like we were discussing different Snyk issues :)

2022-05-25 23:14 UTC, JcolemanNR approved these changes
If this still passes all integration tests, then I think it will be good to eliminate some Snyk issues!

2022-05-27 21:05 UTC, michaelgoin approved these changes

2022-05-27 21:05 UTC, merged