Remove CastleMonoRail2 instrumentation.
newrelic/newrelic-dotnet-agent pull request #1177
Opened 2022-06-29 22:32 UTC by vuqtran88

Thank you for submitting a pull request.  Please review our [contributing guidelines](/CONTRIBUTING.md) and [code of conduct](https://opensource.newrelic.com/code-of-conduct/).

## Description

The what, the why and the how of your PR.

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

2022-06-29 22:43 UTC, JcolemanNR requested changes
Looks good, but since this a deprecation (similar to the logging instrumentation deprecation), we should do the following:

- [ ] Add the instrumentation XML to the instrumentation ignore list in the profiler.
- [ ] Attempt to remove the DLL/XML in the MSI
- [ ] Attempt to remove the DLL/XML in the Azure Site Extension (I think there is prior art)

2022-06-30 17:59 UTC, vuqtran88 commented
@JcolemanNR I added the change as requested, except for the Azure Site Extension. With the change in the profiler, the risk is nearly 0 so i don't think it is worth to do the update.

2022-06-30 21:22 UTC, nr-ahemsath commented on src/Agent/CHANGELOG.md
> +* Castle.Monorail v2 instrumentation has been reomoved. ([#1177])(https://github.com/newrelic/newrelic-dotnet-agent/pull/1177)
```suggestion
* Castle.Monorail instrumentation has been removed. ([#1177])(https://github.com/newrelic/newrelic-dotnet-agent/pull/1177)
```

I think that by specifying "v2" specifically, somebody might think that we still have instrumentation for other versions of Castle.Monorail, when we don't.
```suggestion
* Castle.Monorail v2 instrumentation has been reomoved. ([#1177])(https://github.com/newrelic/newrelic-dotnet-agent/pull/1177)
```

2022-06-30 21:29 UTC, JcolemanNR approved these changes
As long as the profiler is rebuilt/checked in before this merges to main then I'm fine with thig going in as is without the profiler binaries

2022-06-30 22:59 UTC, nr-ahemsath approved these changes
Looks good to me.  Looks like all review feedback has been handled.  👍

2022-07-01 17:38 UTC, merged