Preview 6 changes and additions
newrelic/newrelic-dotnet-agent pull request #1205
Opened 2022-08-02 20:42 UTC by jaffinito

## Description

Adds .NET 7 apps and build targets for our various integration tests.

**This is currently targetting Preview 6**

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

2022-08-02 23:13 UTC, JcolemanNR requested changes
Looks pretty good! I think to merge this we need to add some steps to the all solutions build to install the .NET 7 SDK in the build/test steps. Another concern is that the majority of our test coverage just moved from .NET 6 to .NET 7, but only the logging tests were updated to restore .NET 6 test coverage. Before merging, I think we should restore more .NET 6 test coverage (especially when consolemf is involved)

2022-08-02 23:13 UTC, JcolemanNR commented on tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
> +    <PackageReference Include="log4net" Version="2.0.13" Condition="'$(TargetFramework)' == 'net6.0'" />
cool, adding back some test coverage? :)

2022-08-02 23:13 UTC, JcolemanNR commented on tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
> +#if NETCOREAPP3_1 || NET48 || NET5_0 || NET6_0 || NET7_0
I don't think we need to itemize all the versions of .NET/.NET Core here anymore after dropping support for .NET Core 2.0/2.1/3.0
```suggestion
#if NETCOREAPP || NET48
```

2022-09-06 15:56 UTC, nr-ahemsath commented
We are keeping this draft PR open as we continue to work on making sure that we will support .NET 7 when it goes GA.

2022-09-07 23:33 UTC, nr-ahemsath commented
> Looks pretty good! I think to merge this we need to add some steps to the all solutions build to install the .NET 7 SDK in the build/test steps.

I made the change to install the .NET 7 preview SDK, but it looks like the version of Visual Studio installed in the `windows-2022` runner (17.3.something) won't pick it up.  This jives with how I had to install Visual Studio 17.4.1 Preview in order to use the .NET 7 Preview 7 SDK on my local system.  I did search for how to install a preview version of Visual Studio in a GHA runner but didn't find anything.

To jog my memory, I looked at what was done last year for .NET 6, and found this PR: https://github.com/newrelic/newrelic-dotnet-agent/pull/790/files.  What's notable is that that PR was merged on 11/4/21, whereas the official GA date for .NET 6 was 11/8/21.  So, it may be that once we get to release candidates for .NET 7, a newer version of Visual Studio and MSBuild will be available and things will start working.

2022-10-21 14:39 UTC, nr-ahemsath commented
Since we merged the other .NET 7 branch, which was initially branched off of this one, this can be closed.

2022-10-21 14:39 UTC, closed without merging