Update changelog for log exception attributes
newrelic/newrelic-dotnet-agent pull request #1242
Opened 2022-09-09 17:18 UTC by jaffinito

## Description

Update changelog for log exception attributes

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

2022-09-09 17:25 UTC, chynesNR submitted a review, later dismissed

2022-09-09 17:25 UTC, JcolemanNR requested changes
Looks pretty good! Just a minor change

2022-09-09 17:25 UTC, JcolemanNR commented on src/Agent/CHANGELOG.md
> +  * The error stack is created using the stack of the inner exception, up to 5 levels deep, just like the in the Agent.
```suggestion
  * The error stack is created using the stack of the inner exception, up to 5 levels deep, just like existing Agent error reporting.
```

2022-09-09 20:37 UTC, JcolemanNR approved these changes
Ship it!

2022-09-12 15:27 UTC, chynesNR approved these changes

2022-09-12 15:59 UTC, merged