Add app logging custom attributes settings
newrelic/newrelic-dotnet-agent pull request #1291
Opened 2022-10-27 19:31 UTC by vuqtran88

## Description

Add app logging custom attributes settings.

2022-10-27 21:26 UTC, nr-ahemsath requested changes
Found a few typos to fix.

2022-10-27 21:26 UTC, nr-ahemsath commented on src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
> +                                                            A comma-separated and case-insensitive string that contains the context attributes that should be added to the log record. Empty means incl
```suggestion
                                                            A comma-separated and case-insensitive string that contains the context attributes that should be added to the log record. Empty means include all.
```

2022-10-27 21:26 UTC, nr-ahemsath commented on src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
> +                                                            A comma-separated and case-insensitive string that contains the context attributes that should NOT be added to the log record. Denylist win
```suggestion
                                                            A comma-separated and case-insensitive string that contains the context attributes that should NOT be added to the log record. "exclude" wins over "include".
```

2022-10-28 16:47 UTC, nr-ahemsath commented on src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
> +                                                            A comma-separated and case-insensitive string that contains the context attributes that should be added to the log record. Empty means incl
```suggestion
                                                            A comma-separated list of case-sensitive strings that define the context attributes that should be added to the log record. Empty means include all.
```

2022-10-28 16:47 UTC, nr-ahemsath commented on src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
> +                                                            A comma-separated and case-insensitive string that contains the context attributes that should NOT be added to the log record. "exclude" wi
```suggestion
                                                            A comma-separated list of case-sensitive strings that define the context attributes that should NOT be added to the log record. "exclude" wins over "include".
```

2022-10-28 16:53 UTC, nr-ahemsath approved these changes
Approved. 👍

2022-10-28 16:54 UTC, chynesNR approved these changes

2022-10-28 16:56 UTC, merged

2024-01-18 13:29 UTC, shegeley commented
If you can please show an example (full or just small conceptual piece of code) with on how to add custom attributes to logs? I can't deduct anything from changes on this PR. 

In [Ruby](https://github.com/newrelic/newrelic-ruby-agent/pull/2084) it's really nice: 
```ruby
NewRelic::Agent.add_custom_log_attributes
```
Is there something like this?

2024-01-18 18:51 UTC, jaffinito commented
The .NET agent doesn't have an API for adding custom attributes to log events directly.  Instead, if you add attributes/properties to the log event in your logging framework, the agent can be configured to capture those automatically.  You can find details on enabling this feature on [this page](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#1-agent), about a quarter of the way down (just after the first yellow important box),  It also has some information on how to include or exclude specific properties if you don't want all of them sent up.

[PR where this was added](https://github.com/newrelic/newrelic-dotnet-agent/pull/1317).

2024-01-19 06:55 UTC, shegeley commented
Thanks for the answer 

I am not an expert with .NET, the platform and it's setup ways, still can't understand much from the original doc. As far as I've got only "static" attributes (that are encoded in XML) can be added with this agent. 

I believe an example added to this conversation or the agent repo itself would be highly appreciated by anyone who wants to add custom log attributes to the .NET add hussle-free.

2024-01-20 00:46 UTC, jaffinito commented
Since each logging framework we support (log4net, NLog, Serilog, Microsoft.Extensions.Logging) often has many different ways to add properties it makes it difficult to add examples that are up to date and extensive enough.  We recommend looking at the individual logging library's documentation for how to add properties to the messages.