feat: add support for MySql.Data version 8.0.33+
newrelic/newrelic-dotnet-agent pull request #1708
Opened 2023-06-08 22:09 UTC by nr-ahemsath

## Description

MySql.Data version 8.0.33 reorganized its methods internally so that all of the methods we instrumented previously (ExecuteReader, ExecuteNonQuery, Read, NextResult) became pass-throughs to async versions that perform the same work.

This PR updates the instrumentation file for the Sql wrapper to add the new async instrumentation points for MySql.Data 8.0.33 and higher.

2023-06-08 23:40 UTC, chynesNR commented on tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
> +    <PackageReference Include="MySql.Data" Version="8.0.33" Condition="'$(TargetFramework)' == 'net7.0'" />
We should probably leave a comment in here that 8.0.33 is a breaking change for us. Otherwise looks good!

2023-06-09 15:51 UTC, jaffinito approved these changes

2023-06-09 16:59 UTC, chynesNR approved these changes

2023-06-09 17:19 UTC, nrcventura requested changes
@nr-ahemsath and I talked about this and noticed that the async methods should be instrumented using the async tracer factory instead of the sync tracer factory so that the correct datastore segment timing will be captured.

2023-06-09 21:17 UTC, nrcventura approved these changes

2023-06-10 15:25 UTC, merged