Update GRPC packages
newrelic/newrelic-dotnet-agent pull request #416
Opened 2021-01-04 23:53 UTC by amweiss

### Description

Fixes #394 by updating GRPC nuget package to fix loading on Linux hosts for .NET 5.0.

### Testing

Ran existing tests with updated dependency.

2021-01-04 23:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-dotnet-agent?pullRequest=416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-dotnet-agent?pullRequest=416) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-dotnet-agent?pullRequest=416) it.</sub>

2021-01-05 14:03 UTC, amweiss commented
Ok, this is now failing at the same point as the markdown only change in #417 so I assume it's a bad test and not the library update.

2021-01-05 20:50 UTC, vuqtran88 requested changes
@amweiss Thanks for submitting a PR. I've done initial review on your PR. The main changes looks good. I would like to ask you to remove unnecessary changes to keep the PR small.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> -    $homeFolderPath = New-item -Path "$Path" -Name "$Name" -Type Directory -Force
unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> -        Copy-Item -Path "$dllPath" -Destination "$Destination\extensions" -Force
unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> -        Copy-Item -Path "$dllPath" -Destination "$Destination\extensions" -Force
unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> -
unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> -    Copy-Item -Path "$RootDirectory\src\Agent\Miscellaneous\NewRelic.Providers.Wrapper.Misc.Instrumentation.xml" -Destination "$Destination\extensions" -Force
unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> -    Copy-Item -Path "$RootDirectory\licenses\LICENSE.txt" -Destination "$Destination" -Force
unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> +        Copy-Item -Path "$grpcDir\runtimes\linux-x64\native\libgrpc_csharp_ext.x64.so" -Destination "$Destination" -Force
👍

2021-01-05 20:50 UTC, vuqtran88 commented on build/build_functions.ps1
> +        Copy-Item -Path "$grpcDir\runtimes\win-x86\native\*.dll" -Destination "$Destination" -Force
👍

2021-01-05 20:50 UTC, vuqtran88 commented on src/Agent/CHANGELOG.md
> -  * Adds MAX_EVENT_SAMPLES_STORED - the maximum number of samples stored for Custom Events.
unnecessary code changes.unnecessary code changes.

2021-01-05 20:50 UTC, vuqtran88 commented on src/Agent/NewRelic/Agent/Core/Core.csproj
> +    <PackageReference Include="Google.Protobuf" Version="3.13.0" />
👍

2021-01-05 21:16 UTC, amweiss commented
> @amweiss Thanks for submitting a PR. I've done initial review on your PR. The main changes looks good. I would like to ask you to remove unnecessary changes to keep the PR small.

Trailing white space re-added, I would recommend you either make a single commit to fix the repo or update the editorconfig so this doesn't keep happening to people who respect the repo style settings: https://github.com/newrelic/newrelic-dotnet-agent/blob/main/.editorconfig#L11

2021-01-05 22:19 UTC, vuqtran88 commented
> > @amweiss Thanks for submitting a PR. I've done initial review on your PR. The main changes looks good. I would like to ask you to remove unnecessary changes to keep the PR small.
> 
> Trailing white space re-added, I would recommend you either make a single commit to fix the repo or update the editorconfig so this doesn't keep happening to people who respect the repo style settings: https://github.com/newrelic/newrelic-dotnet-agent/blob/main/.editorconfig#L11

Agree, but I would like to address it in a different PR for readablity purpose as the real changes was very small as comparing to other changes. I will probably do it as a follow up.

2021-01-05 22:24 UTC, vuqtran88 commented
> Ok, this is now failing at the same point as the markdown only change in #417 so I assume it's a bad test and not the library update.

I think some tests are flickers, some are not set up to be ran by external contributors yet. As far as my validation goes, your changes look great and the main problem is fixed.

2021-01-05 22:25 UTC, vuqtran88 approved these changes
LGTM!

2021-01-05 22:27 UTC, merged

2021-01-05 22:27 UTC, vuqtran88 commented
@amweiss Thanks for your contribution. Cheers !